spring.application.name=demo
spring.datasource.url=jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.schema-locations=classpath:db/schema.sql
mybatis.config-location=classpath:db/mybatis-config.xml
mybatis.mapper-locations=classpath:db/mapper/*.xml
